# Configuration for cargo-deny (https://embarkstudios.github.io/cargo-deny/)

[graph]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [
    "RUSTSEC-2024-0436", # unmaintained advisory for paste dependency in ratatui
    "RUSTSEC-2024-0320", # unmaintained advisory for serde_yaml
]

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Zlib",
    "BSD-3-Clause",
    "ISC",
    "CDLA-Permissive-2.0",
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = [
    { name = "syn" },
]
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
