name: Bug Report
description: Report a reproducible problem
title: "[Bug]: "
labels: ["type: bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
    validations:
      required: true
